[package]
name = "byteme"
version = "1.0.0"
edition = "2021"
license = "apache-2.0"
authors = ["mpw <x@mpw.sh>"]

[dependencies]
anyhow = "1.0"
atty = "0.2.14"
flate2 = "1.0.26"
itertools = "0.10.5"
z85 = "3.0.5"
