name: Build and release binary
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REPOSITORY: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            suffix: ""
            use_cross: false
          - os: macos-latest
            target: aarch64-apple-darwin
            suffix: ""
            use_cross: false
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: ""
            use_cross: false
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            suffix: ""
            use_cross: true
          - os: ubuntu-latest
            target: armv7-unknown-linux-musleabihf
            suffix: ""
            use_cross: true
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            suffix: .exe
            use_cross: false
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cross
        if: matrix.use_cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build with cross
        if: matrix.use_cross
        run: cross build --release --target ${{ matrix.target }}

      - name: Build with cargo
        if: ${{ !matrix.use_cross }}
        run: cargo build --release --target ${{ matrix.target }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.REPOSITORY }}-${{ matrix.target }}
          path: ./target/${{ matrix.target }}/release/${{ env.REPOSITORY }}${{ matrix.suffix }}
          if-no-files-found: error

  release:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/download-artifact@v4

      - name: Move binaries
        run: |
          rm -rf bin && mkdir bin
          mv -f ${{ env.REPOSITORY }}-x86_64-apple-darwin/${{ env.REPOSITORY }} ./bin/${{ env.REPOSITORY }}-x86_64-apple-darwin
          mv -f ${{ env.REPOSITORY }}-aarch64-apple-darwin/${{ env.REPOSITORY }} ./bin/${{ env.REPOSITORY }}-aarch64-apple-darwin
          mv -f ${{ env.REPOSITORY }}-x86_64-unknown-linux-gnu/${{ env.REPOSITORY }} ./bin/${{ env.REPOSITORY }}-x86_64-unknown-linux-gnu
          mv -f ${{ env.REPOSITORY }}-aarch64-unknown-linux-gnu/${{ env.REPOSITORY }} ./bin/${{ env.REPOSITORY }}-aarch64-unknown-linux-gnu
          mv -f ${{ env.REPOSITORY }}-armv7-unknown-linux-musleabihf/${{ env.REPOSITORY }} ./bin/${{ env.REPOSITORY }}-armv7-unknown-linux-musleabihf
          mv -f ${{ env.REPOSITORY }}-x86_64-pc-windows-msvc/${{ env.REPOSITORY }}.exe ./bin/${{ env.REPOSITORY }}-x86_64-pc-windows.exe

      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          generate_release_notes: true
          draft: true
          fail_on_unmatched_files: true
          files: |
            ./bin/${{ env.REPOSITORY }}-x86_64-apple-darwin
            ./bin/${{ env.REPOSITORY }}-aarch64-apple-darwin
            ./bin/${{ env.REPOSITORY }}-x86_64-unknown-linux-gnu
            ./bin/${{ env.REPOSITORY }}-aarch64-unknown-linux-gnu
            ./bin/${{ env.REPOSITORY }}-armv7-unknown-linux-musleabihf
            ./bin/${{ env.REPOSITORY }}-x86_64-pc-windows.exe
